### ISSUE TITLE
Weird server issues when specs run

### ISSUE THREAD

**Issue by ecl1pse** [stripe-ruby-mock/stripe-ruby-mock#10]
Whenever specs run/fail I get this:

```

/Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/dante-0.1.5/lib/dante/runner.rb:159:in `parse_options': invalid option: -f (OptionParser::InvalidOption)
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/dante-0.1.5/lib/dante/runner.rb:50:in `execute'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/stripe-ruby-mock-1.8.4.4/lib/stripe_mock/api/server.rb:21:in `kill_server'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/stripe-ruby-mock-1.8.4.4/lib/stripe_mock/api/server.rb:16:in `block in spawn_server'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:103:in `fork'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:103:in `command'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (3 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:80:in `fork'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (2 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
    from /Users/Bob/.rvm/gems/ruby-1.9.3-p448@someapp/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
    from -e:1:in `<main>'
```

The weird thing is if I don't run Zeus it doesn't even run at all. Very annoying. 

Setup: guard-rspec/zeus

**Comment by andrewmarkle** [comment]
I'm having this same issue. It has nothing to do with Spring / Zeus for me. If I run the whole test suite I get the same error as ecl1pse. But a strange thing happens when I run just the test in questing (that is using StripeMock's server). It seems I get a PostGres error plus it's not even running the tests. Spent the morning trying to get this to work but no luck. 

Here's my logs in case it helps solve this: 
```
$ rspec spec/features/client_subscribes_spec.rb 
Daemon has started successfully


Finished in 0.05252 seconds (files took 5.9 seconds to load)
0 examples, 0 failures
Killing server at ./stripe-mock-server.pid
No stripe-mock-server processes are running
/Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:147:in `async_exec': PG::ConnectionBad: PQsocket() can't get socket descriptor:             SELECT tablename (ActiveRecord::StatementInvalid)
            FROM pg_tables
            WHERE schemaname = ANY (current_schemas(false))
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:147:in `block in query'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:146:in `query'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:91:in `tables'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:23:in `rescue in ensure in disable_referential_integrity'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:20:in `ensure in disable_referential_integrity'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:20:in `disable_referential_integrity'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/active_record/truncation.rb:204:in `clean'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:40:in `clean_with'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:91:in `each'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:91:in `clean_with'
	from /Users/amarkle/Dropbox/Sites/houndapp/spec/support/database_cleaner.rb:3:in `block (2 levels) in <top (required)>'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:350:in `run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `block in run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `each'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:110:in `block in run_specs'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/amarkle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/amarkle/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
	from /Users/amarkle/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
```

And here's my test: 

```
require 'rails_helper'
require 'stripe_mock'


StripeMock.spawn_server

feature "Customer subscribes to her company's plan" do

  background do
    @plan = create(:plan)
  end

  scenario "successfully and creates client in database", js: true do
    StripeMock.start_client

    visit subscription_path(@plan.subscription.guid)

    expect(page).to have_css 'h1', text: "#{@plan.company.name}"
    expect(page).to have_content "$10.00"

    fill_in "name", with: "Toshiro Mifune"
    fill_in "email", with: "toshiro@gmail.com"
    fill_in "Card number", with: "4242424242424242"
    fill_in "cc-exp", with: "03 2020"
    fill_in 'CVC', with: '333'

    click_button 'Subscribe'
    expect(page).to have_content "THANKS"

    StripeMock.stop_client
  end
end
```

**Comment by morgler** [comment]
I get the same error. I don't use zeus or spring, but I use guard. My test suite runs fine, if I just call "rspec spec", but I get the above error from guard.

Using stripe-ruby-mock 2.0.1, rails 4.2, stripe 1.17.3., dante 0.2.0

**Comment by morgler** [comment]
This guard issue could be connected to the problem…

**Comment by kathyonu** [comment]
I use spring and ran into the same problem as described by  ecl1pse  on Jul 27, 2013.
My solution was to move the Gemfile.lock to the trash and run $ bundle
I used that to sort it all out.

**Comment by alexmamonchik** [comment]
@ecl1pse @andrewmarkle  you still have this problem?

**Comment by chadwilken** [comment]
I am having this issue @alexmamonchik

**Comment by meatherly** [comment]
workaround: https://github.com/stripe-ruby-mock/stripe-ruby-mock/issues/219#issuecomment-114231782

**Comment by shqear93** [comment]
Is this fixed or we just use the workaround and that's it??
