### ISSUE TITLE
Stripe::Invoice.upcoming doesn't properly handle periods when billing interval remains unchanged

### ISSUE THREAD

**Issue by aenain** [stripe-ruby-mock/stripe-ruby-mock#723]
Hey, after #722 I have found one more interesting case.

### Versions

Stripe API version: [2020-03-02](https://stripe.com/docs/upgrades#2020-03-02)
Stripe ruby gem version: tested both `5.15.0` and `5.22.0`
Stripe ruby mock gem version: tested both `3.0.1` and current `master` at the time of writing (commit: `0730bdb`)

### Steps to reproduce

```
it 'showcase bugs', :aggregate_failures do
  used_days = 15
  days_in_month = 31.0

  travel_to Time.zone.local(2020, 5, 20, 12, 0, 0)

  stripe_helper = StripeMock.create_test_helper
  product = stripe_helper.create_product
  plan = stripe_helper.create_plan(id: 'professional', interval: 'month', product: product.id, amount: 2400)
  new_plan = stripe_helper.create_plan(id: 'squad', interval: 'month', product: product.id, amount: 4900)

  customer = Stripe::Customer.create(source: stripe_helper.generate_card_token)
  subscription = Stripe::Subscription.create(
    customer: customer.id,
    items: [{ plan: plan.id }]
  )

  travel used_days.days # simulate mid-cycle change

  invoice = Stripe::Invoice.upcoming(
    customer: subscription.customer,
    subscription: subscription.id,
    subscription_proration_date: Time.current.to_i,
    subscription_items: [
      { id: subscription.items.data[0].id, plan: new_plan.id }
    ]
  )

  unused_time = (days_in_month - used_days) / days_in_month * plan.amount
  remaining_time = (days_in_month - used_days) / days_in_month * new_plan.amount
  upcoming_time = new_plan.amount
  expect(invoice.total).to be_within(1).of(-unused_time + remaining_time + upcoming_time)

  # issue: invoice shall be created after current period ends
  expect(invoice.created).to eq subscription.current_period_end
  expect(invoice.period_start).to eq subscription.current_period_start
  expect(invoice.period_end).to eq subscription.current_period_end
end
```

### Actual result

```
Failures:

  1) Billing::Subscriptions::PreviewService.preview  showcase bugs
     Got 3 failures:

     1.1) Failure/Error: expect(invoice.created).to eq subscription.current_period_end

            expected: 1592654400
                 got: 1591272000

            (compared using ==)
          # ./spec/services/billing/subscriptions/preview_service_spec.rb:150:in `block (4 levels) in <top (required)>'

     1.2) Failure/Error: expect(invoice.period_start).to eq subscription.current_period_start

            expected: 1589976000
                 got: 1591272000

            (compared using ==)
          # ./spec/services/billing/subscriptions/preview_service_spec.rb:151:in `block (4 levels) in <top (required)>'

     1.3) Failure/Error: expect(invoice.period_end).to eq subscription.current_period_end

            expected: 1592654400
                 got: 1591272000

            (compared using ==)
          # ./spec/services/billing/subscriptions/preview_service_spec.rb:152:in `block (4 levels) in <top (required)>'
```

### Expected result

Tests to pass 🟢 

### Investigation

`#issue` invoice shall be created after current period ends if the billing schedule remains the same.

### Related issues

#722 , #542

**Comment by joshm1204** [comment]
What's the Solution for this? I have same issue.
